package protocols;

public enum ProtocolType {
    NICKNAME_TRANSMISSION,
    SECURE_WORD_TRANSMISSION,
    FILE_TRANSMISSION,
    PARTICIPANTS_TRANSMISSION,
    TIME_SYNCHRONIZATION,
    CLIENT_MESSAGE_TRANSMISSION,
    SERVER_MESSAGE_TRANSMISSION;
}
